### ISSUE TITLE
linux 内核无法启动

### ISSUE THREAD

**Issue by HuJun0** [lc-guo/QT-I.MX6ULL#1]
下面是启动打印的内容

Error: FEC1 address not set.
Normal Boot
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
switch to partitions #0, OK
mmc0 is current device
reading boot.scr
** Unable to read file boot.scr **
reading zImage
5706352 bytes read in 257 ms (21.2 MiB/s)
Booting from mmc ...
reading imx6ull-14x14-evk.dtb
** Unable to read file imx6ull-14x14-evk.dtb **
Kernel image @ 0x80800000 [ 0x000000 - 0x571270 ]

Starting kernel ...

**Comment by lc-guo** [comment]
抱歉，现在才看到，从启动打印的消息来看
1. Unable to read file boot.scr 
2. Unable to read file imx6ull-14x14-evk.dtb
可能是 Uboot 产生了错误，另外加载的设备树文件也不正确，请确保你使用的是我分享的 Uboot ，并严格按照我的步骤进行复现，不要使用自己的 Uboot

如果你使用了自己的 Uboot 请确保以下几点内容：

1. 确保 Uboot 中 bootcmd 环境变量内容为如下内容：
bootcmd=fatload mmc 0:1 80800000 zImage; fatload mmc 0:1 83000000 imx6ull-alientek-emmc.dtb; bootz 80800000 - 83000000;
2. 确保 Uboot 中 bootargs 环境变量内容为如下内容：
bootargs=console=ttymxc0,115200 root=/dev/mmcblk0p2 rootwait rw
